### ISSUE TITLE
Issue with Elementium and six 1.11

### ISSUE THREAD

**Issue by prschmid** [actmd/elementium#7]
Copied from an email bug report.

I do the following steps:

1) pip install elementium 

2) 

```python
from selenium import webdriver
from elementium.drivers.se import SeElements
```

3) it crashes with the following errors:

```sh
Traceback (most recent call last):
  File "fb_fill.py", line 15, in <module>
    import elementium.drivers.se
  File "/home/great/myapp/myappenv/local/lib/python2.7/site-packages/elementium/__init__.py", line 4, in <module>
    from . import elements
  File "/home/great/myapp/myappenv/local/lib/python2.7/site-packages/elementium/elements.py", line 14, in <module>
    from elementium.waiters import ConditionElementsWaiter
  File "/home/great/myapp/myappenv/local/lib/python2.7/site-packages/elementium/waiters.py", line 22, in <module>
    class Waiter(six.with_metaclass(abc.ABCMeta, object)):
  File "/home/great/myapp/myappenv/lib/python2.7/abc.py", line 87, in __new__
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

if I downgrade to six 1.10, everything seems to be OK.

**Comment by prschmid** [comment]
I've made the fix that caused this error and pushed a new release: https://pypi.python.org/pypi/elementium/1.1.9
